// Presentation-only sound layer for Bash Fighter. Owns a single
// AudioContext, decodes the small synthesised WAV assets in ../assets
// (generated by scripts/generate-sounds.mjs -- regenerate that instead of
// hand-editing WAVs), and plays them with a hard cap on simultaneous
// voices so a 20-fighter brawl never becomes a wall of noise.
//
// This module has zero knowledge of the sim; callers (packages/app) decide
// *when* to play a sound by observing sim state, never the other way
// round. That keeps audio strictly presentation, matching the renderer's
// own rule.

export type SoundName =
  | 'hit_light'
  | 'hit_medium'
  | 'hit_heavy'
  | 'shield_block'
  | 'jump'
  | 'item_pickup'
  | 'item_use_explosion'
  | 'elimination'
  | 'match_start'
  | 'match_end';

const SOUND_FILES: Record<SoundName, string> = {
  hit_light: 'hit_light.wav',
  hit_medium: 'hit_medium.wav',
  hit_heavy: 'hit_heavy.wav',
  shield_block: 'shield_block.wav',
  jump: 'jump.wav',
  item_pickup: 'item_pickup.wav',
  item_use_explosion: 'item_use_explosion.wav',
  elimination: 'elimination.wav',
  match_start: 'match_start.wav',
  match_end: 'match_end.wav',
};

const AMBIENT_FILE = 'ambient_loop.wav';

const MUTE_STORAGE_KEY = 'bashfighter.audio.muted';
const MAX_VOICES = 10; // hard cap: a 20-fighter FFA must never sound like a wall of noise

export interface PlayOptions {
  /** 0..1 volume multiplier applied on top of the per-sound base gain. */
  gain?: number;
  /** Playback rate variance for a touch of variety on repeated hits. */
  rate?: number;
}

/** Where the WAV assets are served from. The app's vite config serves
 * packages/audio/assets as a static public dir (see app/vite.config.ts);
 * this base path matches that mount point. Overridable for tests/tools. */
export function defaultAssetBase(): string {
  return '/audio/';
}

export class AudioManager {
  private ctx: AudioContext | null = null;
  private masterGain: GainNode | null = null;
  private buffers = new Map<string, AudioBuffer>();
  private loadPromises = new Map<string, Promise<AudioBuffer | null>>();
  private activeVoices: AudioBufferSourceNode[] = [];
  private muted: boolean;
  private ambientSource: AudioBufferSourceNode | null = null;
  private ambientGain: GainNode | null = null;
  private readonly assetBase: string;
  private initialized = false;

  constructor(assetBase: string = defaultAssetBase()) {
    this.assetBase = assetBase;
    let storedMuted = false;
    try {
      storedMuted = localStorage.getItem(MUTE_STORAGE_KEY) === '1';
    } catch {
      // localStorage unavailable (e.g. privacy mode) -- default unmuted.
    }
    this.muted = storedMuted;
  }

  get isMuted(): boolean {
    return this.muted;
  }

  setMuted(muted: boolean): void {
    this.muted = muted;
    if (this.masterGain) this.masterGain.gain.value = muted ? 0 : 1;
    try {
      localStorage.setItem(MUTE_STORAGE_KEY, muted ? '1' : '0');
    } catch {
      // ignore
    }
  }

  toggleMuted(): boolean {
    this.setMuted(!this.muted);
    return this.muted;
  }

  /** Must be called from within a user-gesture event handler (click/
   * keydown), per browser autoplay policy. Safe to call more than once. */
  initOnGesture(): void {
    if (this.initialized) {
      void this.ctx?.resume();
      return;
    }
    this.initialized = true;
    const Ctor = (window as unknown as { AudioContext?: typeof AudioContext; webkitAudioContext?: typeof AudioContext })
      .AudioContext ?? (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
    if (!Ctor) return; // no Web Audio support -- audio is best-effort, never blocks gameplay
    const ctx = new Ctor();
    this.ctx = ctx;
    const gain = ctx.createGain();
    gain.gain.value = this.muted ? 0 : 1;
    gain.connect(ctx.destination);
    this.masterGain = gain;
    // Warm every buffer now so first playback has no decode latency.
    for (const name of Object.keys(SOUND_FILES) as SoundName[]) void this.load(name);
  }

  private async load(name: SoundName): Promise<AudioBuffer | null> {
    const cached = this.buffers.get(name);
    if (cached) return cached;
    const pending = this.loadPromises.get(name);
    if (pending) return pending;
    const promise = this.fetchAndDecode(SOUND_FILES[name]);
    this.loadPromises.set(name, promise);
    const buf = await promise;
    if (buf) this.buffers.set(name, buf);
    return buf;
  }

  private async fetchAndDecode(fileName: string): Promise<AudioBuffer | null> {
    if (!this.ctx) return null;
    try {
      const res = await fetch(`${this.assetBase}${fileName}`);
      if (!res.ok) return null;
      const arr = await res.arrayBuffer();
      return await this.ctx.decodeAudioData(arr);
    } catch {
      return null; // never throw into gameplay code over a missing/bad sound file
    }
  }

  /** Play a one-shot sound. No-ops silently if audio hasn't been
   * initialized yet (initOnGesture not called), if muted, or if the
   * voice cap is full -- callers never need to check any of that. */
  play(name: SoundName, opts: PlayOptions = {}): void {
    if (!this.ctx || !this.masterGain) return;
    this.pruneFinishedVoices();
    if (this.activeVoices.length >= MAX_VOICES) return; // drop rather than steal: newest hits still register visually
    const buf = this.buffers.get(name);
    if (!buf) {
      void this.load(name); // decode for next time; skip this play to avoid audible lag
      return;
    }
    const src = this.ctx.createBufferSource();
    src.buffer = buf;
    src.playbackRate.value = opts.rate ?? 1;
    const gain = this.ctx.createGain();
    gain.gain.value = Math.max(0, Math.min(1, opts.gain ?? 1));
    src.connect(gain);
    gain.connect(this.masterGain);
    src.addEventListener('ended', () => {
      const idx = this.activeVoices.indexOf(src);
      if (idx >= 0) this.activeVoices.splice(idx, 1);
    });
    src.start();
    this.activeVoices.push(src);
  }

  private pruneFinishedVoices(): void {
    // 'ended' events usually handle this, but guard against any that
    // never fired (e.g. context suspended mid-playback).
    if (this.activeVoices.length <= MAX_VOICES) return;
    this.activeVoices = this.activeVoices.slice(-MAX_VOICES);
  }

  /** Starts the quiet looping ambient/menu bed. Idempotent. */
  startAmbient(): void {
    if (!this.ctx || !this.masterGain || this.ambientSource) return;
    void (async () => {
      if (!this.ctx || this.ambientSource) return;
      const buf = await this.fetchAndDecode(AMBIENT_FILE);
      if (!buf || !this.ctx || !this.masterGain || this.ambientSource) return;
      const src = this.ctx.createBufferSource();
      src.buffer = buf;
      src.loop = true;
      const gain = this.ctx.createGain();
      gain.gain.value = 0.35; // ambient sits well under SFX, never competes with hits
      src.connect(gain);
      gain.connect(this.masterGain);
      src.start();
      this.ambientSource = src;
      this.ambientGain = gain;
    })();
  }

  stopAmbient(): void {
    this.ambientSource?.stop();
    this.ambientSource = null;
    this.ambientGain = null;
  }
}
